### PR TITLE
Migrate to 2.x code base

### PR DESCRIPTION
**Pull request by CalebFenton**
Don't merge this yet!

### CODE REVIEW

**Comment by CalebFenton** [comment]
This is a rewrite of almost all the code, so can I get @strazzere or @enovella to check this out and run it a few times as a sanity test? Everything is working on my end. The main breaking change is that it's only python 3.6+ compatible now.

**Comment by strazzere** [comment]
Pulling to a few machines now and I'll get it tested on my flight back to the bay

**Comment by enovella** [comment]
Count me in! Will test it from now on. :)

**Comment by CalebFenton** [comment]
Did this work in any of your environments? If so, I'd like to merge.

**Comment by CalebFenton** [comment]
Unless there are any objections, I'll merge this in the next few days. It's working for me.

**Comment by strazzere** [comment]
Doh, I apparently never submitted my actual feedback. Confirmed working on MacOS Mojave, Ubuntu 17 and Ubuntu 18.10. LGTM to push

**Comment by enovella** [comment]
LGTM2

**Comment by CalebFenton** [comment]
Thanks guys!

**Pull request merged**
