### PR TITLE
fix: change python-yara-dex from VirusTotal to MobSF version in Dockerfile

### PR DESCRIPTION
**Pull request by dummys**

### CODE REVIEW

**Comment by enovella** [comment]
LGTM! Many thanks. What do you think @CalebFenton ?

**Comment by CalebFenton** [comment]
To clarify, because I forgot and had to look this up again, the yara-python repo isn't _broken_. It works, and compiling with the given flags (being replaced by this PR) will work. However, this complicates the install process for most people who just want to `pip install apkid`.

Context aside, now that I'm more familiar with Docker, I think the correct way to do this is just to run `python setup.py install` and have it install `yara-python-dex` from PyPi rather than installing build tools, downloading and compiling from source, and cleaning up. The container will build much faster and you only have to manage dependencies in `setup.py`.

**Comment by CalebFenton** [comment]
See if it works for you now.

Reference: https://github.com/rednaga/APKiD/commit/6224bbdd40f00812b4ce8e2a0a9fb822c2c6547c

**Comment by CalebFenton** [comment]
@dummys thanks for the effort regardless. A fix is always better than an "it broken". :D

**Comment by dummys** [comment]
@CalebFenton the problem for me it's that the yara-python-dex package from PyPi was broken as well.

**Comment by CalebFenton** [comment]
@dummys what was the error? It would build on my laptop but not in Docker and I found it was new because python 3.10. Pip would say it couldn't find a download link. That's why I use python3.9-slim.

Python package management is confusing imo. Features get added, taken out, and added again. I guess that's the cost of backwards compatibility.

**Comment by dummys** [comment]
Yes sure. I think it was the same error as you then.

**Pull request closed without merging**
