### PR TITLE
Added SecNeo

### PR DESCRIPTION
**Pull request by circleous**
SecNeo (http://www.secneo.com/) added

### CODE REVIEW

**Comment by circleous** [comment]
I'm not very sure about using 'and' operand for encryptlib and encrypted_dex. Tried to look back on my stash, older SecNeo didnt use BaseClassLoader for loading encrypted jar. Thus, changed it to 'or'.

**Comment by CalebFenton** [comment]
Hey circleous, thanks for the PR! Looks pretty good.

The "assets/classes0.jar" looks _slightly_ generic. Is this the string that's only found in newer samples? What would be nice is rules for the different versions. That's probably pretty hard since mapping the sample to the version number is non-trivial. But it would be possible to have a "SecNeo (new)" and "SecNeo (old)" if you really don't know version numbers.

If you don't want to bother with creating different versions of the rules, that's fine, but could you post the file hashes of the samples you know are old and new? Then, I could merge this in and figure it out.

**Comment by circleous** [comment]
New : 7e278c7a4a7121cfc9e6544fc0dd18ba826f65737eae2f1747481470b061ca95
Old : 38baae1226ec46f61e4b972b76ce9b68426309c6a913079906f2e2c06363d3f9
I just take a look to the old secneo, Both files have a same class name for application wrapper (Lcom/secneo/apkwrapper/ApplicationWrapper;)

**Comment by CalebFenton** [comment]
Thanks for the hashes and info. I have enough info to do a good search for lots more samples to hopefully make some rules that distinguish between versions.

**Pull request merged**
