### PR TITLE
added zelix klassmaster java obfuscator

### PR DESCRIPTION
**Pull request by Jasi2169**
added zelix klassmaster java obfuscator

### CODE REVIEW

**Comment by CalebFenton** [comment]
Thanks for another submission. I've looked at it and the strings, even though there are four, are all very, very generic looking. Is there anything more specific? A file name, perhaps? Or some bytecode? Let me know if I can help.

**Comment by Jasi2169** [comment]
we need this four invokes
these are main in zelixklassmaster  (and only zelixklassmaster till now) didnot see other packers used this
1. Ljava/util/jar/JarFile;->entries()Ljava/util/Enumeration;
3. Ljava/security/cert/Certificate;->getEncoded()[B
4. Ljava/util/jar/JarEntry;->getName()Ljava/lang/String;
5. Ljava/util/jar/JarEntry;->getSize()J
6. Ljava/util/jar/JarFile;->getInputStream(Ljava/util/zip/ZipEntry;)Ljava/io/InputStream;
7. Ljava/util/jar/JarEntry;->getCertificates()[Ljava/security/cert/Certificate;

**Comment by CalebFenton** [comment]
None of those method names are endemic to the packer. Additionally, they're all really common looking. This _will_ false positive.

**Comment by Jasi2169** [comment]
well i had two targets one was way back in 2013 dont remember name ,the other is game killer
http://4pda.ru/pages/go/?u=http%3A%2F%2Fzntx.cc%2Fbbs%2Fupload%2F956%2F2016%2F01%2F27%2F992_1819530gamekiller_v4.10(cn.mm.gk).apk&e=46589583

both got this ,other packers which maybe i dont know name doesnot contains jarentry stuff ever which came to my way

**Comment by CalebFenton** [comment]
Gamekiller looks a bit like dexguard. There's an interesting lib/armeabi/libhideme.so that looks promising. Also, the strings are decryptable by simplify.

**Comment by Jasi2169** [comment]
i dont know why i get this same error on every target i try with simplyfy see this :-  

C:\Users\JASI\Desktop\Android\Gamekiller_v4.10(cn.mm.gk)>java -jar C:\Users\JASI
\Desktop\Android\Gamekiller_v4.10(cn.mm.gk)\simplify-1.1.0.jar -et 'com/google'
smali
Executing: Lcom/google/ads/internal/ActivationOverlay;->canScrollHorizontally(I)
Z
Exception in thread "main" java.lang.RuntimeException: Error loading class defin
ition: Landroid/icu/text/MessagePatternUtil;
        at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:161)
        at org.cf.smalivm.type.ClassManager.parseClassIfNecessary(ClassManager.j
ava:179)
        at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:117
)
        at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:132
)
        at org.cf.smalivm.type.ClassManager.getVirtualClass(ClassManager.java:11
0)
        at org.cf.smalivm.dex.SmaliClassLoader.findClass(SmaliClassLoader.java:7
8)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.cf.smalivm.context.ClonerFactory.build(ClonerFactory.java:57)
        at org.cf.smalivm.context.ExecutionContext.<init>(ExecutionContext.java:
40)
        at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:19
6)
        at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:18
6)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:87)
        at org.cf.simplify.Launcher.executeClass(Launcher.java:186)
        at org.cf.simplify.Launcher.run(Launcher.java:153)
        at org.cf.simplify.Main.main(Main.java:14)
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Unknown Source)
        at java.io.InputStreamReader.<init>(Unknown Source)
        at org.cf.smalivm.dex.SmaliParser.parse(SmaliParser.java:69)
        at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:158)
        ... 15 more

C:\Users\JASI\Desktop\Android\Gamekiller_v4.10(cn.mm.gk)>

i posted issue here as well :-  https://github.com/CalebFenton/simplify/issues/54  
it was with different app,do not know buy i followed instructions properly!

used gradle 2.14.1 while building simplify

**Comment by CalebFenton** [comment]
With simplify, when you run it over an entire app, that means it's going to try to execute a million methods. There's a good chance something will fuck up. This is why the readme says you should limit it to just a few methods (with `-it`) and you'll probably have better luck. In my case, for this sample, I just tried one method. Thanks for reporting the issue on simplify bro.

Do you have a modern sample for this packer? If not, let's close this PR unless you plan on adding rules that won't FP :D

**Comment by CalebFenton** [comment]
I'm closing this for now since I don't have a sample to properly evaluate the rules. Feel free to re-open if you have a sample hash for me.

**Pull request closed without merging**
