### PR TITLE
Update packers.yara

### PR DESCRIPTION
**Pull request by apkunpacker**
Tightening Rule Based on sample 
https://github.com/rednaga/APKiD/files/6277082/THOPTV_45.2.1.apk.zip

### CODE REVIEW

**Comment by enovella** [comment]
Some remarks:

- Please specify better the title, so we can identify which packer are you updating.
- Perhaps, we can add a sample2 tag with your sample. Verify that this sample is accessible thru Koodoous or VT.
- Have you found more samples with this asset? `assets/libshellx-super.2019.so` What about a regex here?

```sh
   273284  2021-04-05 20:50   assets/libshellx-super.2019.so
   208672  2021-04-05 20:50   lib/armeabi-v7a/libshell-super.2019.so
      408  2021-04-05 20:50   lib/armeabi-v7a/libshella-4.1.0.29.so
   290496  2021-04-05 20:50   lib/arm64-v8a/libshell-super.2019.so
      408  2021-04-05 20:50   lib/arm64-v8a/libshella-4.1.0.29.so
     2436  2021-04-05 20:50   classes2.dex
   260136  2021-04-05 20:50   classes.dex
    36860  2021-04-05 20:49   AndroidManifest.xml
       31  2021-04-05 20:49   assets/tosversion
      120  2021-04-05 20:50   assets/o0oooOO0ooOo.dat
  6541848  2021-04-05 20:50   assets/0OO00l111l1l
       32  2021-04-05 20:50   tencent_stub
```

**Comment by apkunpacker** [comment]
Another sample :
https://koodous.com/apks/acee9632ec30687588098b437b9b21840c9e67201996948473461741b3216f6e
Current APKiD scan :

$ apkid acee9632ec30687588098b437b9b21840c9e67201996948473461741b3216f6e.apk
[+] APKiD 2.1.1 :: from RedNaga :: rednaga.io
[*] acee9632ec30687588098b437b9b21840c9e67201996948473461741b3216f6e.apk
 |-> packer : Tencent's Legu
[*] acee9632ec30687588098b437b9b21840c9e67201996948473461741b3216f6e.apk!classes.dex
 |-> anti_disassembly : non-zero link offset, non-zero link size
 |-> compiler : dexlib 2.x
 |-> packer : Mobile Tencent Protect
$

Another sample used in https://blog.quarkslab.com/a-glimpse-into-tencents-legu-packer.html 
 itself have assets/libshellx-super.2019.so
hash : 708e6967920dcf2789b7183d714e73ab79a2f8b3ca71929b12aadeb2c58c2867
https://github.com/quarkslab/legu_unpacker_2019/blob/master/samples/com.intotherain.voicechange.apk

**Comment by enovella** [comment]
Add this info in the rule please. Also, highlight source code with back-tips

**Review by kharix5 — COMMENTED** [review]
Same for me 
And ovn chat
To schedule 3pm

**Review by its0x08 — APPROVED** [review]

**Pull request closed without merging**
