### PR TITLE
pip package is broken

### PR DESCRIPTION
**Pull request by matandobr**

### CODE REVIEW

**Comment by CalebFenton** [comment]
How is the pip package broken? What problem are you seeing?

**Comment by matandobr** [comment]
This is strange, the error I got was 

> MacBook-Pro-2:~ matandobr$ sudo pip install apkid
> Collecting apkid
>   Downloading apkid-1.0.0-py2.py3-none-any.whl
> Collecting yara-python==3.5.0.999 (from apkid)
>   Could not find a version that satisfies the requirement yara-python==3.5.0.999 (from apkid) (from versions: 3.4.0.0, 3.5.0, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.7.0)
> No matching distribution found for yara-python==3.5.0.999 (from apkid)

But it seems working today, I guess some version issues, Closing thanks!

**Comment by CalebFenton** [comment]
Thanks for looking into this and closing it. I think that error comes from not installing our yara-python fork first. But if you say it's working, I have no idea what that warning is from.

**Comment by nguyenvulong** [comment]
This happened to me too, the reason is because when we cloned the yara-python from this repo - it is no longer 3.5.0.999 but 3.7.0
apkid looked for 3.5.0.999, so it failed

**Pull request closed without merging**
