### PR TITLE
Add ApkEncryptor packer & closes #204

### LINKED ISSUE #204: Add rule for ApkEncryptor
[Apkencrypterv1.7.apk.zip](https://github.com/rednaga/APKiD/files/4132927/Apkencrypterv1.7.apk.zip)

[Samples.zip](https://github.com/rednaga/APKiD/files/4132930/Samples.zip)

add rule for apk encrypter

### PR DESCRIPTION
**Pull request by enovella**
Closes https://github.com/rednaga/APKiD/issues/204

### CODE REVIEW

**Comment by apkunpacker** [comment]
you can remove 
    // $sig1 = "META-INF/FLY.RSA"
    // $sig2 = "META-INF/FLY.SF"
from comments as in all provided sample default inbuild signing cerificate is used . once after using custom certificate these name become invalid

**Comment by CalebFenton** [comment]
Is ApkEncryptor both a packer and an obfuscator? Do these rules detect them separately? I.e. could someone use ApkEncryptor to obfuscate but not pack, and these rules would only detect the obfuscation? (and vice-versa)

**Comment by apkunpacker** [comment]
> Is ApkEncryptor both a packer and an obfuscator? Do these rules detect them separately? I.e. could someone use ApkEncryptor to obfuscate but not pack, and these rules would only detect the obfuscation? (and vice-versa)

its both packer + obfuscater . there is no common file/class/method between them when packer is used or obfuscator is used as packer inject a fix loader dex and obfuscater inject a diffent fixed type of 3 classes which contains large string pool and decryption routine so i think need different rules

**Comment by apkunpacker** [comment]
> Is ApkEncryptor both a packer and an obfuscator? Do these rules detect them separately? I.e. could someone use ApkEncryptor to obfuscate but not pack, and these rules would only detect the obfuscation? (and vice-versa)

its both packer + obfuscater but seems like rule is only made for packer , all the files defind in both rule belong to "Packer" only so i think rule should me merged and out in packer.yara file only

**Pull request merged**
