### PR TITLE
Update to use  Yara v3.11

### PR DESCRIPTION
**Pull request by superpoussin22**
Use yara version 3.11
also reduce docker layers

### CODE REVIEW

**Comment by CalebFenton** [comment]
It looks like yara-python's update of the yara submodule includes our dex patch. So that greatly simplifies things.

I like that you even updated the install instructions. 👍 I also like the idea of reducing docker layers. This is something I just started doing in my other projects.

Once the tests pass, I'll give a more careful review but this looks good. Thanks.

**Comment by CalebFenton** [comment]
Ahh, the tests are failing with `invalid field name "header"` which means that yara-python was not built with `--enable-dex`.

From the original:

```
RUN python setup.py build --enable-dex	
RUN python setup.py install
```

You'll probably want something like:

```
RUN python setup.py build --enable-dex && \
    python setup.py install
````

**Comment by superpoussin22** [comment]
I update the travis build file, it was missing :)

**Comment by superpoussin22** [comment]
I also reduce docker image size :)

**Comment by CalebFenton** [comment]
Well done. Thanks for helping! :D

**Comment by superpoussin22** [comment]
your welcome :)

**Pull request merged**
