### PR TITLE
Update packers.yara

### PR DESCRIPTION
**Pull request by TinyNiko**
add yidun rule

### CODE REVIEW

**Comment by CalebFenton** [comment]
Thanks for the PR! Do you have any file hashes for this rule? I'd like to get string from the native library or a class path from the app in addition to just the library name to help reduce false positives. I'd also be useful in the future to distinguish between versions.

If you want to find some additional strings, that's great, but if not, that's cool too -- just need a hash. :D

**Comment by TinyNiko** [comment]
[http://sj.qq.com/myapp/detail.htm?apkName=com.netease.yanxuan](url) 
you can download from this url

**Comment by circleous** [comment]
`assets/STuBCLaSS.dex` and `assets/libnesec.so`, good candidate for dex and stub. I haven't do some research tho, just quick view to APK.

**Comment by TinyNiko** [comment]
assets/STuBCLaSS.dex  is not a good candidate for this is a WeChat Plugin .

**Comment by circleous** [comment]
Oh right, I thought this is include dex packer.

**Comment by strazzere** [comment]
Gathering some samples of this to do some tests on (some malware apparently has used it as well) --

odd that there are two files most APKs which this rule would detect on;

```
f040f34784f272bb55d1c1cca9dd05ad70a03ddb  ./contents/assets/libnesec.so
f9650b4e032d21c36090896e4a2ab6b851f7c940  ./contents/lib/armeabi/libnesec.so
ecc700c537cec6eecb23139ae6c2923e6dd302dc  ./contents_34/assets/libnesec.so
f48b38503a09938432484bbdafc2d1d2d3e92209  ./contents_34/lib/armeabi/libnesec.so
```

I haven't dug into this further as to why this is the case, though we could potentially make the rule look for this twice opposed to once. Also looking for some Dalvik code which is related to this.

**Comment by strazzere** [comment]
Seems like the issue I raised in simplify may belong to this protector specifically;

```
.class public La/_;
.super Ljava/lang/Object;
.source "a.java"


# virtual methods
.method public a()V
    .registers 2

    .prologue
    .line 5
    #Method index out of bounds: 50062
    #invoke-direct {}, method@50062
    nop

    .line 6
    .local v0, "i":I
    nop

    nop

    .line 7
    return-void
.end method
```
```
.class public La/_;
.super Ljava/lang/Object;
.source "a.java"


# virtual methods
.method public a()V
    .registers 2

    .prologue
    .line 5
    or-int/2addr v0, p11

    if-gt p4, p14, :cond_6c34

    .line 6
    .local v0, "i":I
    nop

    nop

    .line 7
    return-void
    :cond_6c34
.end method
```
```
.class public Lcom/_;
.super Ljava/lang/Object;
.source "a.java"


# virtual methods
.method public a()V
    .registers 2

    .prologue
    .line 5
    double-to-int p3, v0

    move-wide/16 p54870, v0

    .line 6
    .local v0, "i":I
    nop

    .line 7
    return-void
.end method
```
```
.class public La/_;
.super Ljava/lang/Object;
.source "a.java"


# virtual methods
.method public a()V
    .registers 2

    .prologue
    .line 5
    nop

    .line 6
    .local v0, "i":I
    nop

    nop

    .line 7
    return-void
.end method
```
```
.class public Lcom/_;
.super Ljava/lang/Object;
.source "a.java"


# virtual methods
.method public a()V
    .registers 2

    .prologue
    .line 5
    nop

    .line 6
    .local v0, "i":I
    nop

    nop

    .line 7
    return-void
.end method
```

**Comment by strazzere** [comment]
@CalebFenton I accidently auto-merged this with my changes... Can you please check that the changes are sane?

**Comment by CalebFenton** [comment]
@strazzere Oh yeah, your changes seem pretty robust. 👍 

Thanks again for helping @TinyNiko and @circleous :D

**Comment by strazzere** [comment]
Much appreciated @TinyNiko and @circleous !

**Pull request merged**
