### PR TITLE
cryptoshell: old wine (apkguard) in a new bottle (cryptoshell)

### PR DESCRIPTION
**Pull request by enovella**
**Radare2** Dalvik asm proves that CryptoShell is the same that APKGuard:

cryptoshell

Output:
```
> apkid cryptoshell.apk 
[+] APKiD 1.0.0 :: from RedNaga :: rednaga.io
[*] cryptoshell.apk!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
```

I've overwritten the APKGuard rule instead of keeping both. Less code and faster.

Cheers

### CODE REVIEW

**Comment by enovella** [comment]
What about to.....?

### 1) 
Replace this:
`6f20 0100 fe00`
By:
`6f20 ??00 fe00`
at
https://github.com/rednaga/APKiD/pull/68/files#diff-9fd1861bd6c15b2896172295b7706df6L84

### 2) 

Replace this:
`4d0d 0b0c       // aput-object v13, v11, v12`
By:
`4d0d ??0c       // aput-object v13, v11, v12`
at https://github.com/enovella/APKiD/blob/0c27ca25f8fcd26354a6cdecf55f3c7d85b64d5c/apkid/rules/dex/packers.yara#L139

### 3) 
Replace this:
`4d0e 0b0c       // aput-object v14, v11, v12`
By:
`4d0e ??0c       // aput-object v14, v11, v12`
at
https://github.com/enovella/APKiD/blob/0c27ca25f8fcd26354a6cdecf55f3c7d85b64d5c/apkid/rules/dex/packers.yara#L146

**Comment by enovella** [comment]
# New samples:
https://koodous.com/apks?search=2E7C88A7AA7952139E6496965C013E38
https://koodous.com/apks?search=94F7F32432AFC49F64BAC67B5ECA8D13
https://koodous.com/apks?search=E4651E4CD2393A52D331A9259FD9228C
https://koodous.com/apks?search=0089EE27AE8CEBB87E33DE80A7CD1980
https://koodous.com/apks?search=021D1FFE4E37332A2C60581B80A10F24
https://koodous.com/apks?search=1B610337822AF0A951E25E3C883D7214
https://koodous.com/apks?search=2F9AA112C26C3E9BD89C0C09E35140E3
https://koodous.com/apks?search=55AA4E9712DFFECA8342B2300B1D1A51
https://koodous.com/apks?search=5DCB9C47E6E27658FE2ADA897060C088
https://koodous.com/apks?search=69A82530FA2E579F6E7687D1D532F523
https://koodous.com/apks?search=748DB69C2431728AF839952A213190E1
https://koodous.com/apks?search=831DFEA446A50661495639C69B116382
https://koodous.com/apks?search=880E0FD008E73681B138A73E5E0745E0
https://koodous.com/apks?search=B11F82DA455827047F5A373C111997EA
https://koodous.com/apks?search=E18F49E9B3D8C5A903817D93831D06D7
https://koodous.com/apks?search=F9617BEEC1B56EACE79E870CB0925FFD

# APKiD detects all:
```
[+] APKiD 1.0.0 :: from RedNaga :: rednaga.io
[*] ./91a57d03ae9ea4711f53fa54f909c6b30a13ed6fd47357cd44aec818ba0e66ed!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./a6c1caaf449dba90eafaa01607aebf31a8d67d4f022d86d327d98cbff04d0a4a!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./42040d2f9c30371c4019746b70e465bac92b32c27be2448a2259e501ce3f5826!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./f95ae271064811c2ab46179ffcb0f378b96baea82dfa9326d09b35691a597c23!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./6e5eddebbb23a979a4d73f183ad1d51006be6aa713d9215b9c72ad1911dad94c!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./0c930521f15e7c0766cd251ef67ea1ea7a23cfded206e1b0cde8995b403bc840!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./b8290ed59a50b703507b4fb5e5a5e25cc372d62a4578eefff159c020f40e6515!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./e2ffd402d227a4d275ec02f6f2f826d8270729cede7b077f4aa5d6e11d6aa4bb!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./cc32d14cea8c9ff13e95d2a83135ae4b7f4b0bd84388c718d324d559180218fd!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./bc25b715c2acdca33c07c403891428541f86326f32833c99fac3b8ae0b17266c!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./b6f5a294d4b0bee029c2840c3354ed814d0d751d00c9c3d48603ce1f22dae8b3!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./b98d3f4950d07f62f22b4c933416a007298f9f38bebb897be0e31e4399eb39c3!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./262973c4c8ae315602dc50d5fae008a1769915293df9332c00d665a860032293!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./1cf201ff292a49bf96d4add92dda104e6b18c1f1d728c7234aec6dedb7fb64c8!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./bdaae5b9024f6a36897400cae7db1a8314ee7bc1f9d65d58626272b986ae3cfe!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
[*] ./3fc104c7fb8f6419aa5b45a3abfcc545ddb8e225f1b6dcaf5824075cbdf5dddd!classes.dex
 |-> compiler : dexlib 2.x
 |-> packer : APKGuard/CryptoShell
```

**Comment by CalebFenton** [comment]
Is CryptoShell a forked version of APKGuard? Is it maintained by the same people? Is it a new version?

It sounds like it's a fork or a different version, so it would be nice to capture that in the rules.

If it's the same product, just rebranded, I'm ok with simply adding both names and generalizing the rules.

**Comment by enovella** [comment]
It seems to be the same product because the packer has been rebranded in somehow. I am still considering the rule a little bit huge but it's fine.

Creating two rules would overlap with each other.

**Comment by enovella** [comment]
Done @CalebFenton!

**Comment by strazzere** [comment]
Resolved conflicts, LGTM 👍

**Pull request merged**
